### ISSUE TITLE
未能完成该操作，无效的自变量

### ISSUE THREAD

**Issue by jxp98** [sngxpro/QuanX#3]
老哥，我只要用到保存操作时就显弹窗显示  
未能完成该操作，无效的自变量
怎么破额

**Comment by Gsvshshshg** [comment]
这个我也不知道啊哥



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: jxp <notifications@github.com&gt;
发送时间: 2021年2月19日 23:16
收件人: sngxpro/QuanX <QuanX@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[sngxpro/QuanX] 未能完成该操作，无效的自变量 (#3)





 
老哥，我只要用到保存操作时就显弹窗显示
 未能完成该操作，无效的自变量
 怎么破额
