### ISSUE TITLE
请问是否考虑将v2p脚本分类？

### ISSUE THREAD

**Issue by BSDxxxx** [sngxpro/QuanX#8]
京东脚本并不想跑在v2p上

**Comment by sngxpro** [comment]
V2p跑京东脚本完全没问题，很多小盆友在用它跑。相比docker面板不受镜像制约，拉取自定义脚本也很直接，不用再写麻烦的shell。因此没有移除京东的计划。

**Comment by sngxpro** [comment]
V2p跑京东脚本完全没问题，很多小盆友在用它跑。相比docker面板不受镜像制约，拉取自定义脚本也很直接，不用再写麻烦的shell。因此没有移除京东的计划。
